edition = "2021"
fn_params_layout = "Tall"
format_code_in_doc_comments = true
max_width = 100
merge_derives = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
