[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "Core components for the Cursive TUI"
documentation = "https://docs.rs/cursive"
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive_core"
readme = "Readme.md"
repository = "https://github.com/gyscos/cursive"
version = "0.2.0"
edition = "2018"

[package.metadata.docs.rs]
features = ["unstable_scroll", "markdown", "toml"]

[badges.travis-ci]
repository = "gyscos/cursive"

[badges.appveyor]
repository = "gyscos/cursive"

[dependencies]
enum-map = "0.6"
wasmer_enumset = "1"
log = "0.4"
owning_ref = "0.4"
syn = "1.0"
unicode-segmentation = "1"
unicode-width = "0.1"
xi-unicode = "0.3"
libc = "0.2"
crossbeam-channel = "0.5"
lazy_static = "1"
chrono = "0.4"
ahash = "0.6"

[dependencies.toml]
optional = true
version = "0.5"

[dependencies.num]
default-features = false
version = "0.3"

[dependencies.pulldown-cmark]
default-features = false
optional = true
version = "0.8"

[features]
markdown = ["pulldown-cmark"]
unstable_scroll = []

[lib]
name = "cursive_core"
